- Ejercicio 1

In [69]:
import pandas as pd


data = pd.read_csv("datos_arts.csv")

data

,grupo,depto,item,articulo,fecha,precio,unidades,importe
0,15 LIMPIEZA DEL HOGAR,CUIDADO DE LA ROPA,1000025719,1000025719 JABON EN BARRA BULL DOG GLICERINA 2...,19/08/2020,54,7.0,378.0
1,15 LIMPIEZA DEL HOGAR,CUIDADO DE LA ROPA,1000025724,1000025724 JABON LIQUIDO PAR D.P. 800 CC NEVEX...,19/08/2020,136,1.0,136.0
2,15 LIMPIEZA DEL HOGAR,CUIDADO DE LA ROPA,1000025752,1000025752 JABON LIQ NEVEX MATIC MULTIAC DIF D...,19/08/2020,410,1.0,410.0
3,15 LIMPIEZA DEL HOGAR,CUIDADO DE SUPERFICIES,1000025907,1000025907 PANO DE PISO STANDARD 50X55 CM,19/08/2020,79,1.0,79.0
4,15 LIMPIEZA DEL HOGAR,CUIDADO DE SUPERFICIES,1000025908,1000025908 REJILLA 37X37CM.,19/08/2020,59,1.0,59.0
...,...,...,...,...,...,...,...,...
63590,15 LIMPIEZA DEL HOGAR,CUIDADO DE LA ROPA,1000187363,1000187363 JABON LIQUIDO DE ROPA PLUMA 800ML,10/11/2020,50,5.0,250.0
63591,3 COMESTIBLES,GOLOSINAS,1000188100,1000188100 ALFAJOR BOCADO BLANCO TATA x 6,10/11/2020,62,5.0,310.0
63592,3 COMESTIBLES,ACEITES Y GRASAS,1000194151,1000194151 ACEITE DE OLIVA OLIVARES DE ROCHA 5...,10/11/2020,240,2.0,480.0
63593,18 PERFUMERIA,CUIDADO CAPILAR,1000215423,1000215423 SHAMPOO HEAD & SHOULDER COCONUT 180 CC,10/11/2020,259,1.0,259.0
63594,18 PERFUMERIA,CUIDADO CORPORAL,1000218721,1000218721 JABON DOVE ANTIBACTERIAL CUIDA Y PR...,10/11/2020,59,5.0,295.0

Antes de continuar veamos un poco mas como esta compuesto el dataset, si tiene valores nulos o no

In [70]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63595 entries, 0 to 63594
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   grupo     63595 non-null  object
 1   depto     63595 non-null  object
 2   item      63595 non-null  int64
 3   articulo  63595 non-null  object
 4   fecha     63595 non-null  object
 5   precio    63595 non-null  int64
 6   unidades  63595 non-null  float64
 7   importe   63595 non-null  float64
dtypes: float64(2), int64(2), object(4)
memory usage: 3.9+ MB

- Ejercicio 2

In [71]:
import numpy as np
ejercicio2 = pd.pivot_table(data[["fecha", "articulo", "importe"]], index = "fecha",  aggfunc = {"articulo": np.count_nonzero, "importe": np.sum})
ejercicio2.columns = ["cantidad_articulos", "total_importe"]
ejercicio2

            cantidad_articulos  total_importe
fecha
01/09/2020                 725      187805.51
01/10/2020                 714      217737.20
01/11/2020                 769      244827.88
02/09/2020                 777      236752.26
02/10/2020                 846      280201.06
...                        ...            ...
30/08/2020                 806      246807.36
30/09/2020                 683      188665.76
30/10/2020                 801      252455.86
31/08/2020                 664      182605.31
31/10/2020                 852      287103.04

[84 rows x 2 columns]

- Ejercicio 3

Antes veamos como esta compuesta la columna grupo

In [72]:
data["grupo"].unique()

array(['15 LIMPIEZA DEL HOGAR', '18 PERFUMERIA', '4 LACTEOS', '1 BEBIDAS',
       '3 COMESTIBLES', '9 FIAMBRERIA'], dtype=object)

In [73]:
sector = ["NO COMESTIBLES" if e == "15 LIMPIEZA DEL HOGAR" or e == "18 PERFUMERIA" else "PERECEDEROS" if e == "4 LACTEOS" or e == "9 FIAMBRERIA"
              else e for e in data["grupo"]]
data["SECTOR"] = sector
data

,grupo,depto,item,articulo,fecha,precio,unidades,importe,SECTOR
0,15 LIMPIEZA DEL HOGAR,CUIDADO DE LA ROPA,1000025719,1000025719 JABON EN BARRA BULL DOG GLICERINA 2...,19/08/2020,54,7.0,378.0,NO COMESTIBLES
1,15 LIMPIEZA DEL HOGAR,CUIDADO DE LA ROPA,1000025724,1000025724 JABON LIQUIDO PAR D.P. 800 CC NEVEX...,19/08/2020,136,1.0,136.0,NO COMESTIBLES
2,15 LIMPIEZA DEL HOGAR,CUIDADO DE LA ROPA,1000025752,1000025752 JABON LIQ NEVEX MATIC MULTIAC DIF D...,19/08/2020,410,1.0,410.0,NO COMESTIBLES
3,15 LIMPIEZA DEL HOGAR,CUIDADO DE SUPERFICIES,1000025907,1000025907 PANO DE PISO STANDARD 50X55 CM,19/08/2020,79,1.0,79.0,NO COMESTIBLES
4,15 LIMPIEZA DEL HOGAR,CUIDADO DE SUPERFICIES,1000025908,1000025908 REJILLA 37X37CM.,19/08/2020,59,1.0,59.0,NO COMESTIBLES
...,...,...,...,...,...,...,...,...,...
63590,15 LIMPIEZA DEL HOGAR,CUIDADO DE LA ROPA,1000187363,1000187363 JABON LIQUIDO DE ROPA PLUMA 800ML,10/11/2020,50,5.0,250.0,NO COMESTIBLES
63591,3 COMESTIBLES,GOLOSINAS,1000188100,1000188100 ALFAJOR BOCADO BLANCO TATA x 6,10/11/2020,62,5.0,310.0,3 COMESTIBLES
63592,3 COMESTIBLES,ACEITES Y GRASAS,1000194151,1000194151 ACEITE DE OLIVA OLIVARES DE ROCHA 5...,10/11/2020,240,2.0,480.0,3 COMESTIBLES
63593,18 PERFUMERIA,CUIDADO CAPILAR,1000215423,1000215423 SHAMPOO HEAD & SHOULDER COCONUT 180 CC,10/11/2020,259,1.0,259.0,NO COMESTIBLES
63594,18 PERFUMERIA,CUIDADO CORPORAL,1000218721,1000218721 JABON DOVE ANTIBACTERIAL CUIDA Y PR...,10/11/2020,59,5.0,295.0,NO COMESTIBLES

- Ejercicio 4

In [76]:
import re


data["mes"] = pd.to_datetime(data["fecha"], format = "%d/%m/%Y") + pd.offsets.MonthEnd(0)

ejercicio4 = pd.pivot_table(data, index = ["mes"], columns = ["SECTOR"], values = ["precio", "importe"], aggfunc= {"importe": np.sum, "precio": np.mean})

ejercicio4.columns = ejercicio4.columns.droplevel()
columnas = ejercicio4.columns
regex = re.compile("\d\s")

columnas = [e if len(regex.findall(e)) == 0 else e[2:] for e in columnas]

parteFinal = ["_sum_importe"]*4 + ["_prom_precio"]*4


nuevasColumnas = [e1 + e2 for e1, e2 in zip(columnas, parteFinal)]

ejercicio4.columns = nuevasColumnas
ejercicio4 = ejercicio4[['COMESTIBLES_prom_precio', 'COMESTIBLES_sum_importe', 'BEBIDAS_prom_precio','BEBIDAS_sum_importe',
            'NO COMESTIBLES_prom_precio', 'NO COMESTIBLES_sum_importe', 
            'PERECEDEROS_prom_precio', 'PERECEDEROS_sum_importe']]

ejercicio4 = ejercicio4.sort_index()

ejercicio4.index = pd.Series(ejercicio4.index).dt.month_name(locale = "Spanish")

ejercicio4

,COMESTIBLES_prom_precio,COMESTIBLES_sum_importe,BEBIDAS_prom_precio,BEBIDAS_sum_importe,NO COMESTIBLES_prom_precio,NO COMESTIBLES_sum_importe,PERECEDEROS_prom_precio,PERECEDEROS_sum_importe
mes,,,,,,,,
Agosto,91.468567,1727381.0,83.386125,422772.0,157.137782,858257.0,133.497332,243598.69
Septiembre,94.749433,3880378.0,82.462464,941169.0,162.002069,1582818.0,133.279035,555445.80
Octubre,94.469502,3910410.0,82.257487,1098715.0,168.017672,1678903.0,130.341440,589202.55
Noviembre,98.359850,1224818.0,82.567224,342759.0,176.228571,558243.0,128.697605,194587.12